version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: translationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ******
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/translationdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ******
      JWT_SECRET: "this_is_a_very_secret_jwt_key_1234567890"
      JWT_EXPIRATION: 86400000
    command: ["java", "-Dspring.config.additional-location=optional:classpath:/application.yml", "-jar", "app.jar"]

volumes:
  pgdata:
